<?php
function gb_theme_icon($atts)
{
	extract(shortcode_atts(array(
		"type" => "features",
		"icon_feature" => "address",
		"icon_social" => "angies-list",
		"icon_template" => "arrow-circle",
		"url" => "",
		"url_target" => 'same_window',
		"title" => '',
		"class" => '',
		"top_margin" => "none"
	), $atts));
	$output = '';
	$output .= '<' . ($url!="" ? 'a' : 'span') . ($url!="" ? ' href="' . esc_attr($url) . '"' . ($url_target=="new_window" ? ' target="_blank"' : '') : '') . ' class="icon-single gb-icon ' . esc_attr($type) . '-' . ($type=="features" ? esc_attr($icon_feature) : ($type=="social" ? esc_attr($icon_social) : esc_attr($icon_template))) . ($class!="" ? ' ' . esc_attr($class) : '') . ($top_margin!="none" ? ' ' . esc_attr($top_margin) : '') . '"' . ($title!="" ? ' title="' . esc_attr($title) . '"' : '') . '></' . ($url!="" ? 'a' : 'span') . '>';
	return $output;
}

//visual composer
$icons_features = array(
	__("address", 'gymbase') => "address",
	__("app", 'gymbase') => "app",
	__("apple", 'gymbase') => "apple",
	__("arrows", 'gymbase') => "arrows",
	__("bar-graph", 'gymbase') => "bar-graph",
	__("battery", 'gymbase') => "battery",
	__("bicycle", 'gymbase') => "bicycle",
	__("book", 'gymbase') => "book",
	__("box", 'gymbase') => "box",
	__("boxing", 'gymbase') => "boxing",
	__("brain", 'gymbase') => "brain",
	__("briefcase", 'gymbase') => "briefcase",
	__("burns", 'gymbase') => "burns",
	__("calendar-info", 'gymbase') => "calendar-info",
	__("calendar-plus", 'gymbase') => "calendar-plus",
	__("calendar-tick", 'gymbase') => "calendar-tick",
	__("cart", 'gymbase') => "cart",
	__("certificate", 'gymbase') => "certificate",
	__("chart-1", 'gymbase') => "chart-1",
	__("chart-2", 'gymbase') => "chart-2",
	__("chat", 'gymbase') => "chat",
	__("clock", 'gymbase') => "clock",
	__("config", 'gymbase') => "config",
	__("coupon", 'gymbase') => "coupon",
	__("credit-card", 'gymbase') => "credit-card",
	__("cross", 'gymbase') => "cross",
	__("cycling", 'gymbase') => "cycling",
	__("diary", 'gymbase') => "diary",
	__("dna", 'gymbase') => "dna",
	__("document", 'gymbase') => "document",
	__("document-missing", 'gymbase') => "document-missing",
	__("drink", 'gymbase') => "drink",
	__("dumbbell-1", 'gymbase') => "dumbbell-1",
	__("dumbbell-2", 'gymbase') => "dumbbell-2",
	__("email", 'gymbase') => "email",
	__("facebook", 'gymbase') => "facebook",
	__("first-aid", 'gymbase') => "first-aid",
	__("gallery", 'gymbase') => "gallery",
	__("glasses", 'gymbase') => "glasses",
	__("graph", 'gymbase') => "graph",
	__("group-1", 'gymbase') => "group-1",
	__("group-2", 'gymbase') => "group-2",
	__("gym-1", 'gymbase') => "gym-1",
	__("gym-2", 'gymbase') => "gym-2",
	__("hand-grip", 'gymbase') => "hand-grip",
	__("hand-squeezer", 'gymbase') => "hand-squeezer",
	__("heart", 'gymbase') => "heart",
	__("heart-beat", 'gymbase') => "heart-beat",
	__("home", 'gymbase') => "home",
	__("id-1", 'gymbase') => "id-1",
	__("id-2", 'gymbase') => "id-2",
	__("id-3", 'gymbase') => "id-3",
	__("image", 'gymbase') => "image",
	__("keyboard", 'gymbase') => "keyboard",
	__("lab", 'gymbase') => "lab",
	__("laptop", 'gymbase') => "laptop",
	__("leaf", 'gymbase') => "leaf",
	__("lifeline", 'gymbase') => "lifeline",
	__("list", 'gymbase') => "list",
	__("location", 'gymbase') => "location",
	__("lock", 'gymbase') => "lock",
	__("lockers", 'gymbase') => "lockers",
	__("map", 'gymbase') => "map",
	__("martial-art", 'gymbase') => "martial-art",
	__("medical-bed", 'gymbase') => "medical-bed",
	__("medical-document", 'gymbase') => "medical-document",
	__("medical-results", 'gymbase') => "medical-results",
	__("minus", 'gymbase') => "minus",
	__("mobile", 'gymbase') => "mobile",
	__("money", 'gymbase') => "money",
	__("movie", 'gymbase') => "movie",
	__("muscle", 'gymbase') => "muscle",
	__("network", 'gymbase') => "network",
	__("paypal", 'gymbase') => "paypal",
	__("pen", 'gymbase') => "pen",
	__("people", 'gymbase') => "people",
	__("percent", 'gymbase') => "percent",
	__("phone", 'gymbase') => "phone",
	__("pill", 'gymbase') => "pill",
	__("pin", 'gymbase') => "pin",
	__("pingpong", 'gymbase') => "pingpong",
	__("play", 'gymbase') => "play",
	__("plus", 'gymbase') => "plus",
	__("presentation", 'gymbase') => "presentation",
	__("printer", 'gymbase') => "printer",
	__("protein", 'gymbase') => "protein",
	__("pulse", 'gymbase') => "pulse",
	__("scale", 'gymbase') => "scale",
	__("science", 'gymbase') => "science",
	__("screen", 'gymbase') => "screen",
	__("shower", 'gymbase') => "shower",
	__("signpost", 'gymbase') => "signpost",
	__("sneakers", 'gymbase') => "sneakers",
	__("soccer", 'gymbase') => "soccer",
	__("spa", 'gymbase') => "spa",
	__("spa-bamboo", 'gymbase') => "spa-bamboo",
	__("spa-lotion", 'gymbase') => "spa-lotion",
	__("speaker", 'gymbase') => "speaker",
	__("squash", 'gymbase') => "squash",
	__("stopwatch", 'gymbase') => "stopwatch",
	__("tablet", 'gymbase') => "tablet",
	__("tags", 'gymbase') => "tags",
	__("tennis", 'gymbase') => "tennis",
	__("test-tube", 'gymbase') => "test-tube",
	__("tick", 'gymbase') => "tick",
	__("time", 'gymbase') => "time",
	__("twitter", 'gymbase') => "twitter",
	__("video", 'gymbase') => "video",
	__("wallet", 'gymbase') => "wallet",
	__("weightlifting", 'gymbase') => "weightlifting",
	__("youtube", 'gymbase') => "youtube"
);
$icons_social = array(
	__("angies-list", 'gymbase') => "angies-list",
	__("behance", 'gymbase') => "behance",
	__("deviantart", 'gymbase') => "deviantart",
	__("dribbble", 'gymbase') => "dribbble",
	__("email", 'gymbase') => "email",
	__("envato", 'gymbase') => "envato",
	__("facebook", 'gymbase') => "facebook",
	__("flickr", 'gymbase') => "flickr",
	__("foursquare", 'gymbase') => "foursquare",
	__("github", 'gymbase') => "github",
	__("google-plus", 'gymbase') => "google-plus",
	__("houzz", 'gymbase') => "houzz",
	__("instagram", 'gymbase') => "instagram",
	__("linkedin", 'gymbase') => "linkedin",
	__("location", 'gymbase') => "location",
	__("mobile", 'gymbase') => "mobile",
	__("paypal", 'gymbase') => "paypal",
	__("pinterest", 'gymbase') => "pinterest",
	__("reddit", 'gymbase') => "reddit",
	__("rss", 'gymbase') => "rss",
	__("skype", 'gymbase') => "skype",
	__("soundcloud", 'gymbase') => "soundcloud",
	__("spotify", 'gymbase') => "spotify",
	__("stumbleupon", 'gymbase') => "stumbleupon",
	__("tumblr", 'gymbase') => "tumblr",
	__("twitter", 'gymbase') => "twitter",
	__("whatsapp", 'gymbase') => "whatsapp",
	__("weibo", 'gymbase') => "weibo",
	__("vimeo", 'gymbase') => "vimeo",
	__("vine", 'gymbase') => "vine",
	__("vk", 'gymbase') => "vk",
	__("xing", 'gymbase') => "xing",
	__("yelp", 'gymbase') => "yelp",
	__("youtube", 'gymbase') => "youtube"
);
$icons_template = array(
	__("arrow-circle", 'gymbase') => "arrow-circle",
	__("arrow-horizontal-1", 'gymbase') => "arrow-horizontal-1",
	__("arrow-horizontal-2", 'gymbase') => "arrow-horizontal-2",
	__("arrow-horizontal-3", 'gymbase') => "arrow-horizontal-3",
	__("arrow-horizontal-4", 'gymbase') => "arrow-horizontal-4",
	__("arrow-horizontal-5", 'gymbase') => "arrow-horizontal-5",
	__("arrow-horizontal-6", 'gymbase') => "arrow-horizontal-6",
	__("arrow-horizontal-7", 'gymbase') => "arrow-horizontal-7",
	__("arrow-vertical-1", 'gymbase') => "arrow-vertical-1",
	__("arrow-vertical-3", 'gymbase') => "arrow-vertical-3",
	__("arrow-vertical-4", 'gymbase') => "arrow-vertical-4",
	__("arrow-vertical-5", 'gymbase') => "arrow-vertical-5",
	__("arrow-vertical-6", 'gymbase') => "arrow-vertical-6",
	__("arrow-vertical-7", 'gymbase') => "arrow-vertical-7",
	__("cart", 'gymbase') => "cart",
	__("check", 'gymbase') => "check",
	__("chevron", 'gymbase') => "chevron",
	__("comment-1", 'gymbase') => "comment-1",
	__("comment-2", 'gymbase') => "comment-2",
	__("email", 'gymbase') => "email",
	__("location", 'gymbase') => "location",
	__("menu-1", 'gymbase') => "menu-1",
	__("menu-2", 'gymbase') => "menu-2",
	__("minus-1", 'gymbase') => "minus-1",
	__("minus-2", 'gymbase') => "minus-2",
	__("mobile", 'gymbase') => "mobile",
	__("plus-1", 'gymbase') => "plus-1",
	__("plus-2", 'gymbase') => "plus-2",
	__("remove-1", 'gymbase') => "remove-1",
	__("remove-2", 'gymbase') => "remove-2",
	__("search", 'gymbase') => "search",
	__("tick-1", 'gymbase') => "tick-1",
	__("tick-2", 'gymbase') => "tick-2",
	__("quote", 'gymbase') => "quote",
	__("quote-2", 'gymbase') => "quote-2"
);

vc_map( array(
	"name" => __("Icon", 'gymbase'),
	"base" => "gb_icon",
	"class" => "",
	"controls" => "full",
	"show_settings_on_create" => true,
	"icon" => "icon-wpb-layer-icon",
	"category" => __('GymBase', 'gymbase'),
	"params" => array(
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Type", 'gymbase'),
			"param_name" => "type",
			"value" => array(__("Feature", 'gymbase') => "features", __("Social", 'gymbase') => "social", __("Template", 'gymbase') => "template")
		),
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Icon", 'gymbase'),
			"param_name" => "icon_feature",
			"value" => $icons_features,
			"dependency" => Array('element' => "type", 'value' => array('features'))
		),
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Icon", 'gymbase'),
			"param_name" => "icon_social",
			"value" => $icons_social,
			"dependency" => Array('element' => "type", 'value' => array('social'))
		),
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Icon", 'gymbase'),
			"param_name" => "icon_template",
			"value" => $icons_template,
			"dependency" => Array('element' => "type", 'value' => array('template'))
		),
		array(
			"type" => "textfield",
			"class" => "",
			"heading" => __("Url", 'gymbase'),
			"param_name" => "url",
			"value" => ""
		),
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Url target", 'gymbase'),
			"param_name" => "url_target",
			"value" => array(
				__("same window", 'gymbase') => 'same_window',
				__("new window", 'gymbase') => 'new_window'
			)
		),
		array(
			"type" => "textfield",
			"class" => "",
			"heading" => __("Title", 'gymbase'),
			"param_name" => "title",
			"value" => ""
		),
		array(
			"type" => "textfield",
			"holder" => "div",
			"class" => "",
			"heading" => __("Extra class name", 'gymbase'),
			"param_name" => "class",
			"value" => ""
		),
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Top margin", 'gymbase'),
			"param_name" => "top_margin",
			"value" => array(__("None", 'gymbase') => "none", __("Page (small)", 'gymbase') => "page-margin-top", __("Section (large)", 'gymbase') => "page-margin-top-section")
		)
	)
));
?>
